### ISSUE TITLE
TODO list for new Symmetries

### ISSUE THREAD

**Issue by gabrielfougeron** [gabrielfougeron/choreo#134]
Regarding the spectral solver:

- [x] params_to_segmpos
- [x] segmpos_to_params
- [x] #135
- [x] Action, Action grad and Action hessian
+ Idem, optimized for the case where all binary segment transformations are Identity
EDIT : Even better, code a one size fits all with a precomputed `bint[::1]` switch
- [x] Hash !!!

Regarding the RK solver:
- [x] fun and gun.
- [x] Periodicity default

Other:
- [x] Save / load from / to disk
- [x] Conversions of the old format to the new format
